
// Replacements for Nuxt UI's default component icons (normally lucide), keyed by the names
// accepted by the vite plugin's `ui.icons` option, so the UI only uses Material Symbols.
// All UI icons (these + any used in components) are bundled locally at build time via the
// plugin's `icon.clientBundle` option in vite.config.ts — none are fetched from the iconify
// API at runtime. Cover *background* icons are unrelated — the generator fetches those
export const nuxt_ui_icons = {
    arrowDown: 'material-symbols:arrow-downward',
    arrowLeft: 'material-symbols:arrow-back',
    arrowRight: 'material-symbols:arrow-forward',
    arrowUp: 'material-symbols:arrow-upward',
    caution: 'material-symbols:error',
    check: 'material-symbols:check',
    chevronDoubleLeft: 'material-symbols:keyboard-double-arrow-left',
    chevronDoubleRight: 'material-symbols:keyboard-double-arrow-right',
    chevronDown: 'material-symbols:keyboard-arrow-down',
    chevronLeft: 'material-symbols:keyboard-arrow-left',
    chevronRight: 'material-symbols:keyboard-arrow-right',
    chevronUp: 'material-symbols:keyboard-arrow-up',
    close: 'material-symbols:close',
    copy: 'material-symbols:content-copy',
    copyCheck: 'material-symbols:library-add-check',
    dark: 'material-symbols:dark-mode',
    drag: 'material-symbols:drag-indicator',
    ellipsis: 'material-symbols:more-horiz',
    error: 'material-symbols:cancel',
    external: 'material-symbols:arrow-outward',
    eye: 'material-symbols:visibility',
    eyeOff: 'material-symbols:visibility-off',
    file: 'material-symbols:draft',
    folder: 'material-symbols:folder',
    folderOpen: 'material-symbols:folder-open',
    hash: 'material-symbols:tag',
    info: 'material-symbols:info',
    light: 'material-symbols:light-mode',
    loading: 'material-symbols:progress-activity',
    menu: 'material-symbols:menu',
    minus: 'material-symbols:remove',
    panelClose: 'material-symbols:left-panel-close',
    panelOpen: 'material-symbols:left-panel-open',
    plus: 'material-symbols:add',
    reload: 'material-symbols:refresh',
    search: 'material-symbols:search',
    star: 'material-symbols:star',
    stop: 'material-symbols:stop',
    success: 'material-symbols:check-circle',
    system: 'material-symbols:computer',
    tip: 'material-symbols:lightbulb',
    upload: 'material-symbols:upload',
    warning: 'material-symbols:warning',
}
