
// Serialise all computed cover data into a Typst _data.typ file

import {mm_to_typst} from './utils.js'
import {escape_typst_str} from 'typst-utils'
import type {CoverSchema} from './schema.js'
import type {GetDimensionsResult} from 'printing-services'
import type {ResolvedColors} from './design.js'
import type {FontSizes} from './font_sizes.js'

/** Helper: emit a Typst #let binding for a millimetre value */
function mmval(name:string, mm:number):string {
    return `#let ${name} = ${mm_to_typst(mm)}`
}

/** Helper: emit a Typst #let binding for a string */
function str(name:string, value:string):string {
    return `#let ${name} = "${escape_typst_str(value)}"`
}

/** Helper: emit a Typst #let binding for a boolean */
function bool(name:string, value:boolean):string {
    return `#let ${name} = ${value ? 'true' : 'false'}`
}

/** Helper: emit a Typst #let binding for a color from an hsl(Hdeg, S%, L%) string, or none */
function color(name:string, hsl_str:string | null):string {
    if (hsl_str === null)
        return `#let ${name} = none`
    // hsl(Hdeg, S%, L%) → color.hsl(Hdeg, S%, L%) — same args, CSS-compatible format
    return `#let ${name} = color.${hsl_str}`
}

/** Helper: emit a Typst #let binding for a content block with pre-built Typst markup */
function content_raw(name:string, value:string):string {
    return `#let ${name} = [${value}]`
}

/** Helper: emit a Typst #let binding for a number */
function num(name:string, value:number):string {
    return `#let ${name} = ${value}`
}

/**
 * Build the full _data.typ file content from all computed cover data.
 * The Typst template imports this file to receive all variables.
 */
export function build_data_file(
    schema:CoverSchema,
    dims:GetDimensionsResult,
    colors:ResolvedColors,
    font_body_family:string,
    font_title1_family:string,
    font_title2_family:string,
    font_title3_family:string,
    font_subtitle_family:string,
    font_author_family:string,
    font_blurb_family:string,
    font_spine_title_family:string,
    font_spine_author_family:string,
    font_sizes:FontSizes,
    image_filename:string | null,
    has_barcode:boolean,
    has_icon:boolean,
    has_pattern:boolean,
    pattern_aspect_ratio?:number,
):string {
    const lines:string[] = ['// Auto-generated by paper_cover generator — do not edit', '']

    // Total dimensions
    lines.push('// Total dimensions')
    lines.push(mmval('total_width', dims.cover_total_width.toNumber()))
    lines.push(mmval('total_height', dims.cover_total_height.toNumber()))
    lines.push(mmval('bleed', dims.cover_bleed.toNumber()))
    lines.push(mmval('face_width', dims.cover_face_width.toNumber()))
    lines.push(mmval('face_height', dims.cover_face_height.toNumber()))
    lines.push(mmval('spine_width', dims.cover_spine.toNumber()))
    lines.push(mmval('back_x', dims.cover_region_back.x.toNumber()))
    lines.push(mmval('spine_x', dims.cover_region_spine.x.toNumber()))
    lines.push(mmval('front_x', dims.cover_region_front.x.toNumber()))
    // Barcode region (x from canvas left, y from trim bottom)
    lines.push(mmval('barcode_x', dims.cover_region_barcode.x.toNumber()))
    lines.push(mmval('barcode_y', dims.cover_region_barcode.y.toNumber()))
    lines.push(mmval('barcode_w', dims.cover_region_barcode.w.toNumber()))
    lines.push(mmval('barcode_h', dims.cover_region_barcode.h.toNumber()))
    lines.push(bool('has_spine', dims.cover_has_spine))
    lines.push(bool('has_spine_text', dims.cover_has_spine_text))
    lines.push(bool('has_bleed', dims.cover_has_bleed))
    lines.push('')

    const {subtitle_lines} = font_sizes

    // Text content
    lines.push('// Text content')
    lines.push(str('title1', (schema.title1 ?? '').trim()))
    lines.push(str('title2', (schema.title2 ?? '').trim()))
    lines.push(str('title3', (schema.title3 ?? '').trim()))
    const subtitle_lines_typst = subtitle_lines.map(l => `"${escape_typst_str(l)}"`).join(', ')
    lines.push(`#let subtitle_lines = (${subtitle_lines_typst}${subtitle_lines_typst ? ',' : ''})`)
    lines.push(str('spine_title', schema.spine_title ?? ''))
    lines.push(str('spine_author', schema.spine_author ?? ''))
    lines.push(str('author', schema.author ?? ''))
    lines.push(str('isbn', schema.isbn ?? ''))
    lines.push(content_raw('blurb', schema.blurb ?? ''))
    lines.push(bool('has_title1', !!(schema.title1?.trim())))
    lines.push(bool('has_title2', !!(schema.title2?.trim())))
    lines.push(bool('has_title3', !!(schema.title3?.trim())))
    lines.push(bool('has_subtitle', !!(schema.subtitle)))
    lines.push(bool('has_author', !!(schema.author)))
    lines.push(bool('has_blurb', !!(schema.blurb)))
    lines.push('')

    // Per-text sizing (relative multipliers, default 1.0)
    lines.push('// Per-text sizing')
    lines.push(num('title1_size', schema.title1_size ?? 1))
    lines.push(num('title2_size', schema.title2_size ?? 1))
    lines.push(num('title3_size', schema.title3_size ?? 1))
    lines.push(num('subtitle_size', schema.subtitle_size ?? 1))
    lines.push(num('author_size', schema.author_size ?? 1))
    lines.push(num('blurb_size', schema.blurb_size ?? 1))
    lines.push(num('spine_title_size_mod', schema.spine_title_size ?? 1))
    lines.push(num('spine_author_size_mod', schema.spine_author_size ?? 1))
    lines.push('')

    // Colors
    lines.push('// Colors')
    lines.push(bool('has_front_gradient', !!(schema.bg_color_gradient)))
    lines.push(color('color_front_bg', colors.front_background))
    lines.push(color('color_front_gradient_start', colors.front_gradient_start))
    lines.push(color('color_front_gradient_end', colors.front_gradient_end))
    lines.push(color('color_back_bg', colors.back_background))
    lines.push(color('color_spine_bg', colors.spine_background))
    // Per-title colors (auto-contrast defaults resolved in design.ts)
    lines.push(color('color_front_title1', colors.front_title1))
    lines.push(color('color_front_title2', colors.front_title2))
    lines.push(color('color_front_title3', colors.front_title3))
    lines.push(color('color_front_subtitle', colors.front_subtitle))
    lines.push(color('color_front_author', colors.front_author))
    lines.push(color('color_blurb', colors.blurb))
    lines.push(color('color_blurb_bg', colors.blurb_background))
    lines.push(color('color_spine_title', colors.spine_title))
    lines.push(color('color_spine_author', colors.spine_author))
    lines.push(color('color_accent', colors.accent))
    lines.push('')

    // Typography
    lines.push('// Typography')
    lines.push(str('font_body_family', font_body_family))
    lines.push(str('font_title1_family', font_title1_family))
    lines.push(str('font_title2_family', font_title2_family))
    lines.push(str('font_title3_family', font_title3_family))
    lines.push(str('font_subtitle_family', font_subtitle_family))
    lines.push(str('font_author_family', font_author_family))
    lines.push(str('font_blurb_family', font_blurb_family))
    lines.push(str('font_spine_title_family', font_spine_title_family))
    lines.push(str('font_spine_author_family', font_spine_author_family))
    lines.push(num('title1_weight', schema.title1_weight ?? 700))
    lines.push(bool('title1_italic', schema.title1_italic ?? false))
    lines.push(num('title2_weight', schema.title2_weight ?? 700))
    lines.push(bool('title2_italic', schema.title2_italic ?? false))
    lines.push(num('title3_weight', schema.title3_weight ?? 700))
    lines.push(bool('title3_italic', schema.title3_italic ?? false))
    lines.push(num('subtitle_weight', schema.subtitle_weight ?? 100))
    lines.push(bool('subtitle_italic', schema.subtitle_italic ?? false))
    lines.push(num('author_weight', schema.author_weight ?? 400))
    lines.push(bool('author_italic', schema.author_italic ?? false))
    lines.push(num('spine_title_weight', schema.spine_title_weight ?? 700))
    lines.push(bool('spine_title_italic', schema.spine_title_italic ?? false))
    lines.push(num('spine_author_weight', schema.spine_author_weight ?? 400))
    lines.push(bool('spine_author_italic', schema.spine_author_italic ?? false))
    lines.push(mmval('fs_back_blurb', font_sizes.back_blurb))
    lines.push(mmval('fs_spine_title', font_sizes.spine_title))
    lines.push(mmval('fs_spine_author', font_sizes.spine_author))
    lines.push('')

    // Element positions and alignment
    lines.push('// Element positions and alignment')
    lines.push(str('title_position', schema.title_position))
    lines.push(str('subtitle_position', schema.subtitle_position))
    lines.push(str('author_position', schema.author_position))
    // Alignment emitted as raw Typst values (left/center/right)
    lines.push(`#let title_alignment = ${schema.title_alignment ?? 'center'}`)
    lines.push(`#let subtitle_alignment = ${schema.subtitle_alignment ?? 'center'}`)
    lines.push(`#let author_alignment = ${schema.author_alignment ?? 'center'}`)
    const blurb_align = schema.blurb_alignment ?? 'left'
    lines.push(`#let blurb_alignment = ${blurb_align === 'justified' ? 'left' : blurb_align}`)
    lines.push(bool('blurb_justify', blurb_align === 'justified'))
    lines.push('')

    // Panel margins (all 4 sides of each panel, resolved to mm)
    lines.push('// Panel margins')
    const face_height_mm = dims.cover_face_height.toNumber()
    const face_width_mm = dims.cover_face_width.toNumber()
    const cover_margin_mm = dims.cover_margin.toNumber()
    // Blurb padding (% of face_width, resolved to mm) — computed early as back margin depends on it
    const min_blurb_padding_mm = 5
    const blurb_padding_mm = Math.max(
        face_height_mm * (schema.blurb_padding ?? 1) / 100, min_blurb_padding_mm)
    // Front minimum is 0.5" or the service's cover margin, whichever is greater
    const min_front_margin_mm = Math.max(13, cover_margin_mm)  // 13mm = ~0.5"
    // Back minimum is cover margin minus blurb padding (blurb sits inside the margin)
    const min_back_margin_mm = cover_margin_mm - blurb_padding_mm
    const front_margin_mm = Math.max(
        face_height_mm * (schema.margin_front ?? 10) / 100, min_front_margin_mm,
    )
    const back_margin_mm = Math.max(
        face_height_mm * (schema.margin_back ?? 10) / 100, min_back_margin_mm,
    )
    lines.push(mmval('front_margin', front_margin_mm))
    lines.push(mmval('back_margin', back_margin_mm))
    // Derived content areas
    lines.push(mmval('front_content_w', face_width_mm - front_margin_mm * 2))
    lines.push(mmval('front_content_h', face_height_mm - front_margin_mm * 2))
    lines.push(mmval('back_content_w', face_width_mm - back_margin_mm * 2))
    lines.push(mmval('back_content_h', face_height_mm - back_margin_mm * 2))
    // Blurb width (% of face_width, clamped to back content width)
    const back_content_w_mm = face_width_mm - back_margin_mm * 2
    const blurb_w_mm = Math.min(
        face_width_mm * (schema.blurb_width ?? 80) / 100, back_content_w_mm,
    )
    lines.push(mmval('blurb_width', blurb_w_mm))
    lines.push(mmval('blurb_padding', blurb_padding_mm))
    lines.push(num('blurb_spacing', schema.blurb_spacing ?? 1))
    lines.push('')

    // Vertical margins (% of face height)
    lines.push('// Vertical margins')
    lines.push(num('title_spacing', schema.title_spacing ?? 3))
    lines.push(num('title_margin_top', schema.title_margin_top ?? 10))
    lines.push(num('title_margin_bottom', schema.title_margin_bottom ?? 10))
    lines.push(num('subtitle_spacing', schema.subtitle_spacing ?? 1.5))
    lines.push(num('subtitle_margin_top', schema.subtitle_margin_top ?? 10))
    lines.push(num('subtitle_margin_bottom', schema.subtitle_margin_bottom ?? 10))
    lines.push(num('author_margin_top', schema.author_margin_top ?? 10))
    lines.push(num('author_margin_bottom', schema.author_margin_bottom ?? 10))
    lines.push('')

    // Image, icon, and barcode
    lines.push('// Assets')
    lines.push(bool('has_image', image_filename !== null))
    lines.push(str('image_filename', image_filename ?? ''))
    lines.push(str('image_coverage', schema.bg_image_coverage ?? 'front'))
    lines.push(bool('has_icon', has_icon))
    lines.push(str('icon_mode', schema.icon_mode ?? 'center'))
    lines.push(num('icon_size_mod', schema.icon_size ?? 1))
    // Spine icon shown when icon_spine is enabled and the spine is wide enough for text
    lines.push(bool('has_spine_icon', has_icon && (schema.icon_spine ?? false) && dims.cover_has_spine_text))
    lines.push(bool('has_barcode', has_barcode))
    lines.push(bool('has_pattern', has_pattern))
    // Tile width from schema; height derived from SVG's natural aspect ratio so non-square patterns tile correctly
    const pattern_tile_w = schema.pattern_tile_mm ?? 80
    const pattern_tile_h = pattern_aspect_ratio ? pattern_tile_w / pattern_aspect_ratio : pattern_tile_w
    lines.push(mmval('pattern_tile_w', pattern_tile_w))
    lines.push(mmval('pattern_tile_h', pattern_tile_h))
    lines.push('')

    return lines.join('\n')
}
